Repository GeekGiggle/hacktoberfest, pull requests merged in 2024-10, with the labels that each got.

#14 Added new name
  ToDoList/index.html
  ToDoList/script.js
  ToDoList/style.css
  entry.html
Labels: hacktoberfest, hacktoberfest-accepted

#13 Added Calculator app project
  calculator/MoonIcon.svg
  calculator/SunIcon.svg
  calculator/calculator.js
  calculator/download (1).ico
  calculator/index.html
  calculator/package-lock.json
  calculator/package.json
  calculator/public/index.html
  calculator/src/App.css
  calculator/src/App.js
  calculator/src/index.js
  calculator/style.css
  calculator/style2.css
Labels: hacktoberfest, hacktoberfest-accepted, first issue, hacktoberfest2024

#15 Added my name to the list!
  entry.html
Labels: good first issue, hacktoberfest, hacktoberfest-accepted, hacktoberfest2024

#10 Currency Converter
  currency-converter/.gitignore
  currency-converter/README.md
  currency-converter/eslint.config.js
  currency-converter/index.html
  currency-converter/package-lock.json
  currency-converter/package.json
  currency-converter/postcss.config.js
  currency-converter/public/vite.svg
  currency-converter/src/App.css
  currency-converter/src/App.jsx
  currency-converter/src/assets/react.svg
  currency-converter/src/components/Inputbox.jsx
  currency-converter/src/components/index.js
  currency-converter/src/hooks/useCurrencyInfo.js
  currency-converter/src/index.css
  currency-converter/src/main.jsx
  currency-converter/tailwind.config.js
  currency-converter/vite.config.js
Labels: good first issue, hacktoberfest, hacktoberfest-accepted, first issue, hacktoberfest2024, first-contributions

#9 Added new name in name branch in entry.html
  entry.html
Labels: hacktoberfest, hacktoberfest-accepted, first issue, hacktoberfest2024, first-contributions

#16 Added my name to the contributors list .
  entry.html
Labels: hacktoberfest, hacktoberfest-accepted, first issue, hacktoberfest2024

#18 First non-code contribution in hacktoberfest 2024
  entry.html
Labels: good first issue, hacktoberfest, hacktoberfest-accepted, first issue, first-timers, hacktoberfest2024, first-contributions

#22 Simen Game added
  Simen-Game/index.html
  Simen-Game/script.js
  Simen-Game/style.css
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2024

#21 food app project added
  .gitignore
  NewsApp/.gitignore
  NewsApp/README.md
  NewsApp/package-lock.json
  NewsApp/package.json
  NewsApp/public/favicon.ico
  NewsApp/public/index.html
  NewsApp/public/manifest.json
  NewsApp/sampleOutput.json
  NewsApp/src/App.css
  NewsApp/src/App.js
  NewsApp/src/Components/Navbar.js
  NewsApp/src/Components/News.js
  NewsApp/src/Components/NewsItem.js
  NewsApp/src/Components/Spinner.js
  NewsApp/src/Components/loading.gif
  NewsApp/src/index.css
  NewsApp/src/index.js
  NewsApp/src/logo.svg
  NewsApp/src/reportWebVitals.js
  NewsApp/src/setupTests.js
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2024

#20 Added files for JavaScript Quote Generation
  Js_Quote_Generator/app.js
  Js_Quote_Generator/index.html
Labels: hacktoberfest-accepted, opensource, hacktoberfest2024

#24 Issue resolved regarding colors in simen game project.
  Simen-Game/index.html
  Simen-Game/script.js
  Simen-Game/style.css
Labels: hacktoberfest, hacktoberfest-accepted

#29 Dice roller Project
  Dice-Roller-project/index.html
  Dice-Roller-project/script.js
  Dice-Roller-project/style.css
  To-do-list-project/index.html
  To-do-list-project/script.js
  To-do-list-project/style.css
Labels: hacktoberfest, hacktoberfest-accepted

#27 Added BigO and Diwali Sales Analysis
  BigO/bigo.ipynb
  BigO/bigo.py
  DiwaliSalesAnalysis/Diwali Sales Data.csv
  DiwaliSalesAnalysis/DiwaliSalesAnalysis.ipynb
  DiwaliSalesAnalysis/DiwaliSalesAnalysis.py
Labels: hacktoberfest-accepted

#26 Enhance To-Do List App: Light Background and Improved Task Management
  ToDoListApp/index.html
  ToDoListApp/script.js
  ToDoListApp/styles.css
Labels: hacktoberfest-accepted

#25 Added DrumKit using javascript
  DrumKitGame/.DS_Store
  DrumKitGame/images/crash.png
  DrumKitGame/images/kick.png
  DrumKitGame/images/snare.png
  DrumKitGame/images/tom1.png
  DrumKitGame/images/tom2.png
  DrumKitGame/images/tom3.png
  DrumKitGame/images/tom4.png
  DrumKitGame/index.html
  DrumKitGame/index.js
  DrumKitGame/sounds/crash.mp3
  DrumKitGame/sounds/kick-bass.mp3
  DrumKitGame/sounds/snare.mp3
  DrumKitGame/sounds/tom-1.mp3
  DrumKitGame/sounds/tom-2.mp3
  DrumKitGame/sounds/tom-3.mp3
  DrumKitGame/sounds/tom-4.mp3
  DrumKitGame/styles.css
Labels: hacktoberfest-accepted

#37 Added Qr Code Generator
  QrCode generator/QRCode Generator/index.html
  QrCode generator/QRCode Generator/script.js
  QrCode generator/QRCode Generator/style.css
Labels: good first issue, hacktoberfest, hacktoberfest2024

#34 Added a Ping Pong Score Keeper Project
  Score-Keeper/README.md
  Score-Keeper/app.js
  Score-Keeper/index.html
  Score-Keeper/style.css
Labels: hacktoberfest, hacktoberfest-accepted

#54 feat: add quiz app component with score tracking and responsive UI
  Quizz App/css/Picsart_23-08-23_16-23-17-790.png
  Quizz App/css/pexels-miguel-á-padriñán-19670.jpg
  Quizz App/css/quiz.css
  Quizz App/index.html
  Quizz App/js/data.js
  Quizz App/js/quizz.js
Labels: hacktoberfest-accepted

#52 #hacktoberfest'24
  calculator/calculator.js
  calculator/package.json
  calculator/style.css
  package-lock.json
Labels: hacktoberfest-accepted

#51 Added Color Pallet Generator
  Color-pallette-generator/index.html
  Color-pallette-generator/script.js
  Color-pallette-generator/style.css
  entry.html
Labels: hacktoberfest-accepted

#45 Create tic-tac-toe.py
  tic-tac-toe.py
Labels: hacktoberfest-accepted

#69 WeatherApp
  WeatherApp/WeatherApp/images/clear.png
  WeatherApp/WeatherApp/images/clouds.png
  WeatherApp/WeatherApp/images/drizzle.png
  WeatherApp/WeatherApp/images/humidity.png
  WeatherApp/WeatherApp/images/mist.png
  WeatherApp/WeatherApp/images/rain.png
  WeatherApp/WeatherApp/images/search.png
  WeatherApp/WeatherApp/images/snow.png
  WeatherApp/WeatherApp/images/wind.png
  WeatherApp/WeatherApp/index.html
  WeatherApp/WeatherApp/style.css
Labels: hacktoberfest-accepted

#71 Add Guess The Flag iOS game
  GuessTheFlag/Assets.xcassets/AccentColor 1.colorset/Contents.json
  GuessTheFlag/Assets.xcassets/AccentColor.colorset/Contents.json
  GuessTheFlag/Assets.xcassets/AppIcon 1.appiconset/Contents.json
  GuessTheFlag/Assets.xcassets/AppIcon.appiconset/Contents.json
  GuessTheFlag/Assets.xcassets/Contents.json
  GuessTheFlag/Assets.xcassets/Estonia.imageset/Contents.json
  GuessTheFlag/Assets.xcassets/Estonia.imageset/Estonia@2x.png
  GuessTheFlag/Assets.xcassets/Estonia.imageset/Estonia@3x.png
  GuessTheFlag/Assets.xcassets/France.imageset/Contents.json
  GuessTheFlag/Assets.xcassets/France.imageset/France@2x.png
  GuessTheFlag/Assets.xcassets/France.imageset/France@3x.png
  GuessTheFlag/Assets.xcassets/Germany.imageset/Contents.json
  GuessTheFlag/Assets.xcassets/Germany.imageset/Germany@2x.png
  GuessTheFlag/Assets.xcassets/Germany.imageset/Germany@3x.png
  GuessTheFlag/Assets.xcassets/Ireland.imageset/Contents.json
  GuessTheFlag/Assets.xcassets/Ireland.imageset/Ireland@2x.png
  GuessTheFlag/Assets.xcassets/Ireland.imageset/Ireland@3x.png
  GuessTheFlag/Assets.xcassets/Italy.imageset/Contents.json
  GuessTheFlag/Assets.xcassets/Italy.imageset/Italy@2x.png
  GuessTheFlag/Assets.xcassets/Italy.imageset/Italy@3x.png
  GuessTheFlag/Assets.xcassets/Monaco.imageset/Contents.json
  GuessTheFlag/Assets.xcassets/Monaco.imageset/Monaco@2x.png
  GuessTheFlag/Assets.xcassets/Monaco.imageset/Monaco@3x.png
  GuessTheFlag/Assets.xcassets/Nigeria.imageset/Contents.json
  GuessTheFlag/Assets.xcassets/Nigeria.imageset/Nigeria@2x.png
  GuessTheFlag/Assets.xcassets/Nigeria.imageset/Nigeria@3x.png
  GuessTheFlag/Assets.xcassets/Poland.imageset/Contents.json
  GuessTheFlag/Assets.xcassets/Poland.imageset/Poland@2x.png
  GuessTheFlag/Assets.xcassets/Poland.imageset/Poland@3x.png
  GuessTheFlag/Assets.xcassets/Russia.imageset/Contents.json
  GuessTheFlag/Assets.xcassets/Russia.imageset/Russia@2x.png
  GuessTheFlag/Assets.xcassets/Russia.imageset/Russia@3x.png
  GuessTheFlag/Assets.xcassets/Spain.imageset/Contents.json
  GuessTheFlag/Assets.xcassets/Spain.imageset/Spain@2x.png
  GuessTheFlag/Assets.xcassets/Spain.imageset/Spain@3x.png
  GuessTheFlag/Assets.xcassets/UK.imageset/Contents.json
  GuessTheFlag/Assets.xcassets/UK.imageset/UK@2x.png
  GuessTheFlag/Assets.xcassets/UK.imageset/UK@3x.png
  GuessTheFlag/Assets.xcassets/US.imageset/Contents.json
  GuessTheFlag/Assets.xcassets/US.imageset/US@2x.png
  GuessTheFlag/Assets.xcassets/US.imageset/US@3x.png
  GuessTheFlag/ContentView.swift
  GuessTheFlag/GuessTheFlagApp.swift
  GuessTheFlag/Preview Content/Preview Assets.xcassets/Contents.json
Labels: hacktoberfest-accepted
